FROM ocaml/opam:alpine-ocaml-5.3 AS build
RUN opam-2.2 update

ADD . /home/opam/vpnkit
RUN sudo chown opam:opam -R vpnkit
WORKDIR /home/opam/vpnkit
RUN opam-2.2 pin add vpnkit /home/opam/vpnkit --kind=path -n

RUN opam-2.2 install vpnkit -y -t

# unit tests
RUN opam-2.2 exec -- dune runtest
# integration tests
RUN opam-2.2 exec -- dune build @e2e

# we're not interested in the intermediate artifacts
FROM scratch
COPY --from=build /home/opam/vpnkit/_build/log /
