FROM linuxkit/alpine:77f48acc94bdda04e7be1e501a234c2b5c0d6593 AS mirror

RUN apk add --no-cache go musl-dev build-base

ADD . /go/src/github.com/moby/vpnkit/go
WORKDIR /go/src/github.com/moby/vpnkit/go

RUN GOPATH=/go make test
RUN GOPATH=/go make build/dial-example.linux

